language: go

git:
  depth: false

sudo: required

dist: bionic

services:
  - docker

go:
  - 1.14

before_install:
  - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md)|(\.png)|(\.pdf)|(\.html)|^(LICENSE)|^(docs)|^(OWNERS)|^(MAINTAINERS)'
      then
        echo "Only doc files were updated, skip running the CI."
        travis_terminate 0
      fi

install:
  - go get github.com/onsi/ginkgo/ginkgo
  - go get sigs.k8s.io/kind@v0.7.0
  - go mod vendor
  - sudo apt-get update && sudo apt-get install -y apt-transport-https
  - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
  - sudo apt-get update
  - sudo apt-get install -y kubectl

jobs:
  include:
    - stage: "kubernetes e2e test"
      name: "for api-machinery"
      arch: amd64
      script:
        - make kubernetes_e2e WHAT=api-machinery
    - name: "kubernetes e2e test for apps"
      arch: amd64
      script:
        - make kubernetes_e2e WHAT=apps
    - name: "kubernetes e2e test for instrumentation"
      arch: amd64
      script:
        - make kubernetes_e2e WHAT=instrumentation
    - name: "kubernetes e2e test for network"
      arch: amd64
      script:
        - make kubernetes_e2e WHAT=network
    - name: "kubernetes e2e test for node"
      arch: amd64
      script:
        - make kubernetes_e2e WHAT=node
    - name: "kubernetes e2e test for scheduling"
      arch: amd64
      script:
        - make kubernetes_e2e WHAT=scheduling
    - name: "kubernetes e2e test for storage"
      arch: amd64
      script:
        - make kubernetes_e2e WHAT=storage
