language: go

git:
  depth: false

sudo: required

dist: bionic

services:
  - docker

go:
  - 1.13

before_install:
  - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md)|(\.png)|(\.pdf)|(\.html)|^(LICENSE)|^(docs)'
      then
        echo "Only doc files were updated, skip running the CI."
        travis_terminate 0
      fi

install: true

jobs:
  include:
    - stage: "Verify vendor, codegen, gofmt, golint, govet"
      name: "Verify vendor, codegen, gofmt, golint, govet"
      before_script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | BINARY=golangci-lint sh -s -- -d -b $(go env GOPATH)/bin v1.22.2
        - export GO111MODULE=on
      script:
        - make verify
        - make lint

    - stage: "Test on amd64"
      name: "build, crossbuild"
      arch: amd64
      before_script:
        - sudo apt-get install upx-ucl -y
        - export GOFLAGS=-mod=vendor
      script:
        - make bluetoothdevice
        - make all
        - make crossbuild
        - make crossbuild ARCH=arm
        - make crossbuild ARCH=arm64
    - name: "unit test, integration test edge"
      arch: amd64
      before_script:
        - sudo apt-get install upx-ucl -y
        - go get github.com/onsi/ginkgo/ginkgo
        - export GOFLAGS=-mod=vendor
      script:
        - make test
        - make integrationtest
    - name: "e2e test"
      arch: amd64
      before_script:
        - go get github.com/onsi/ginkgo/ginkgo
        - go get sigs.k8s.io/kind@v0.7.0
        - export GOFLAGS=-mod=vendor
        - sudo apt-get update && sudo apt-get install -y apt-transport-https
        - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        - echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
        - sudo apt-get update
        - sudo apt-get install -y kubectl
      script:
        - travis_retry make e2e
    - name: "keadm e2e test"
      arch: amd64
      before_script:
        - go get github.com/onsi/ginkgo/ginkgo
        - go get sigs.k8s.io/kind@v0.7.0
        - export GOFLAGS=-mod=vendor
        - sudo apt-get update && sudo apt-get install -y apt-transport-https
        - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        - echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
        - sudo apt-get update
        - sudo apt-get install -y kubectl
      script:
        - travis_retry make keadm_e2e
    - name: "build docker images on amd64"
      arch: amd64
      script:
        - make image

    - stage: "Test on arm64"
      name: "unit test"
      arch: arm64
      before_script:
        - export GOFLAGS=-mod=vendor
      script:
        - make test
    - name: "build docker images on arm64"
      arch: arm64
      script:
        - make image
