# Default values for cloudcore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: kubeedge/cloudcore
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

serviceAccount:
  # Annotations to add to the service account
  annotations: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  create: false
  # type: NodePort
  # port: 32000

resources:
  limits:
    cpu: 200m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
